// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class PersonneImpl_Stub
    extends java.rmi.server.RemoteStub
    implements Personne, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_addLivre_0;
    private static java.lang.reflect.Method $method_getId_1;
    private static java.lang.reflect.Method $method_getLivres_2;
    private static java.lang.reflect.Method $method_getNom_3;
    private static java.lang.reflect.Method $method_getPrenom_4;
    private static java.lang.reflect.Method $method_getRole_5;
    private static java.lang.reflect.Method $method_notification_6;
    private static java.lang.reflect.Method $method_returnLivre_7;
    private static java.lang.reflect.Method $method_setId_8;
    private static java.lang.reflect.Method $method_setNom_9;
    private static java.lang.reflect.Method $method_setPrenom_10;
    private static java.lang.reflect.Method $method_setRole_11;
    
    static {
	try {
	    $method_addLivre_0 = Personne.class.getMethod("addLivre", new java.lang.Class[] {Livre.class});
	    $method_getId_1 = Personne.class.getMethod("getId", new java.lang.Class[] {});
	    $method_getLivres_2 = Personne.class.getMethod("getLivres", new java.lang.Class[] {});
	    $method_getNom_3 = Personne.class.getMethod("getNom", new java.lang.Class[] {});
	    $method_getPrenom_4 = Personne.class.getMethod("getPrenom", new java.lang.Class[] {});
	    $method_getRole_5 = Personne.class.getMethod("getRole", new java.lang.Class[] {});
	    $method_notification_6 = Personne.class.getMethod("notification", new java.lang.Class[] {Livre.class});
	    $method_returnLivre_7 = Personne.class.getMethod("returnLivre", new java.lang.Class[] {Livre.class});
	    $method_setId_8 = Personne.class.getMethod("setId", new java.lang.Class[] {long.class});
	    $method_setNom_9 = Personne.class.getMethod("setNom", new java.lang.Class[] {java.lang.String.class});
	    $method_setPrenom_10 = Personne.class.getMethod("setPrenom", new java.lang.Class[] {java.lang.String.class});
	    $method_setRole_11 = Personne.class.getMethod("setRole", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public PersonneImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of addLivre(Livre)
    public void addLivre(Livre $param_Livre_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addLivre_0, new java.lang.Object[] {$param_Livre_1}, 223570500479559697L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getId()
    public long getId()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getId_1, null, -6040770469254561000L);
	    return ((java.lang.Long) $result).longValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getLivres()
    public java.util.List getLivres()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getLivres_2, null, 4539089477864077839L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getNom()
    public java.lang.String getNom()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getNom_3, null, 3886217295678390307L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getPrenom()
    public java.lang.String getPrenom()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getPrenom_4, null, -2055859947152102214L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getRole()
    public java.lang.String getRole()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getRole_5, null, 350326467578808232L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of notification(Livre)
    public void notification(Livre $param_Livre_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_notification_6, new java.lang.Object[] {$param_Livre_1}, -447053712540194883L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of returnLivre(Livre)
    public void returnLivre(Livre $param_Livre_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_returnLivre_7, new java.lang.Object[] {$param_Livre_1}, 8653769903854018799L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setId(long)
    public void setId(long $param_long_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setId_8, new java.lang.Object[] {new java.lang.Long($param_long_1)}, 5551971341729963106L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setNom(String)
    public void setNom(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setNom_9, new java.lang.Object[] {$param_String_1}, -5889446409456961040L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setPrenom(String)
    public void setPrenom(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setPrenom_10, new java.lang.Object[] {$param_String_1}, -2421973547525817181L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setRole(String)
    public void setRole(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setRole_11, new java.lang.Object[] {$param_String_1}, -8416458188504738921L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
